"""add explanation column to practice_questions

Revision ID: 0002_explanation
Revises: 0001_initial
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002_explanation"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # MCQ explanations were generated by the LLM, then silently dropped for
    # want of a column — so every MCQ fell back to "Correct."/"That's not
    # right." Existing rows get NULL and keep that fallback.
    op.add_column("practice_questions", sa.Column("explanation", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("practice_questions", "explanation")
