# -*- coding: utf-8 -*-
# Generated by the gRPC Python protocol compiler plugin.  DO NOT EDIT BY HAND.
# source: search.proto
#
# Regenerate with:  ./scripts/gen_proto.sh
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from embedding_service import search_pb2 as search__pb2

GRPC_GENERATED_VERSION = '1.60.0'


class VectorSearchStub(object):
    """Vector search, embedding, and corpus introspection.

    embedding-service owns Qdrant, BGE-M3 and the sparse vocab. This is the
    only way anything else reaches them.
    """

    def __init__(self, channel):
        self.Search = channel.unary_unary(
            '/slashus.search.v1.VectorSearch/Search',
            request_serializer=search__pb2.SearchRequest.SerializeToString,
            response_deserializer=search__pb2.SearchResponse.FromString,
        )
        self.ListTitles = channel.unary_unary(
            '/slashus.search.v1.VectorSearch/ListTitles',
            request_serializer=search__pb2.ListTitlesRequest.SerializeToString,
            response_deserializer=search__pb2.ListTitlesResponse.FromString,
        )
        self.Embed = channel.unary_unary(
            '/slashus.search.v1.VectorSearch/Embed',
            request_serializer=search__pb2.EmbedRequest.SerializeToString,
            response_deserializer=search__pb2.EmbedResponse.FromString,
        )
        self.Health = channel.unary_unary(
            '/slashus.search.v1.VectorSearch/Health',
            request_serializer=search__pb2.HealthRequest.SerializeToString,
            response_deserializer=search__pb2.HealthResponse.FromString,
        )


class VectorSearchServicer(object):
    """Vector search, embedding, and corpus introspection."""

    def Search(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTitles(self, request, context):
        """Distinct lesson titles for a user — the EXACT stored strings.

        Exists so the caller can match against real titles instead of asking
        a model to invent one. See agents/retrieval/titles.py.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Search': grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=search__pb2.SearchRequest.FromString,
            response_serializer=search__pb2.SearchResponse.SerializeToString,
        ),
        'ListTitles': grpc.unary_unary_rpc_method_handler(
            servicer.ListTitles,
            request_deserializer=search__pb2.ListTitlesRequest.FromString,
            response_serializer=search__pb2.ListTitlesResponse.SerializeToString,
        ),
        'Embed': grpc.unary_unary_rpc_method_handler(
            servicer.Embed,
            request_deserializer=search__pb2.EmbedRequest.FromString,
            response_serializer=search__pb2.EmbedResponse.SerializeToString,
        ),
        'Health': grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=search__pb2.HealthRequest.FromString,
            response_serializer=search__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'slashus.search.v1.VectorSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class VectorSearch(object):
    """Convenience stub for callers that do not hold a channel."""

    @staticmethod
    def Search(request, target, options=(), channel_credentials=None,
               call_credentials=None, insecure=False, compression=None,
               wait_for_ready=None, timeout=None, metadata=None):
        return grpc.experimental.unary_unary(
            request, target, '/slashus.search.v1.VectorSearch/Search',
            search__pb2.SearchRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options, channel_credentials, insecure, call_credentials,
            compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTitles(request, target, options=(), channel_credentials=None,
                   call_credentials=None, insecure=False, compression=None,
                   wait_for_ready=None, timeout=None, metadata=None):
        return grpc.experimental.unary_unary(
            request, target, '/slashus.search.v1.VectorSearch/ListTitles',
            search__pb2.ListTitlesRequest.SerializeToString,
            search__pb2.ListTitlesResponse.FromString,
            options, channel_credentials, insecure, call_credentials,
            compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Embed(request, target, options=(), channel_credentials=None,
              call_credentials=None, insecure=False, compression=None,
              wait_for_ready=None, timeout=None, metadata=None):
        return grpc.experimental.unary_unary(
            request, target, '/slashus.search.v1.VectorSearch/Embed',
            search__pb2.EmbedRequest.SerializeToString,
            search__pb2.EmbedResponse.FromString,
            options, channel_credentials, insecure, call_credentials,
            compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request, target, options=(), channel_credentials=None,
               call_credentials=None, insecure=False, compression=None,
               wait_for_ready=None, timeout=None, metadata=None):
        return grpc.experimental.unary_unary(
            request, target, '/slashus.search.v1.VectorSearch/Health',
            search__pb2.HealthRequest.SerializeToString,
            search__pb2.HealthResponse.FromString,
            options, channel_credentials, insecure, call_credentials,
            compression, wait_for_ready, timeout, metadata)
