# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import search_pb2 as search__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorSearchStub:
    """Vector search, owned by embedding-service.

    embedding-service owns Qdrant, the BGE-M3 model, and the sparse vocab.
    Nothing else touches them. Before this, agentic-service loaded its own copy
    of BGE-M3 (~2.2 GB) and read the same vocab file from a second mount — two
    models on an 8 GB VM, and a vocab that silently went stale in the reader
    whenever ingest appended to it.

    Regenerate stubs after editing:
    python -m grpc_tools.protoc -I shared/proto \
    --python_out=<svc> --grpc_python_out=<svc> shared/proto/search.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/slashus.search.v1.VectorSearch/Search',
                request_serializer=search__pb2.SearchRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/slashus.search.v1.VectorSearch/Embed',
                request_serializer=search__pb2.EmbedRequest.SerializeToString,
                response_deserializer=search__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/slashus.search.v1.VectorSearch/Health',
                request_serializer=search__pb2.HealthRequest.SerializeToString,
                response_deserializer=search__pb2.HealthResponse.FromString,
                _registered_method=True)


class VectorSearchServicer:
    """Vector search, owned by embedding-service.

    embedding-service owns Qdrant, the BGE-M3 model, and the sparse vocab.
    Nothing else touches them. Before this, agentic-service loaded its own copy
    of BGE-M3 (~2.2 GB) and read the same vocab file from a second mount — two
    models on an 8 GB VM, and a vocab that silently went stale in the reader
    whenever ingest appended to it.

    Regenerate stubs after editing:
    python -m grpc_tools.protoc -I shared/proto \
    --python_out=<svc> --grpc_python_out=<svc> shared/proto/search.proto

    """

    def Search(self, request, context):
        """One search. Synchronous by design: a user is waiting on it, which is why
        this is gRPC and not a Kafka topic — request/response over a broker means
        reinventing correlation ids and timeouts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Raw vectors. Not used by retrieval today, but it makes the asymmetric
        embedding contract explicit rather than a convention two services
        independently remember to honour.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness for the gRPC port specifically. An HTTP /health passing while
        the gRPC thread is dead is the exact failure that hides a broken service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=search__pb2.SearchRequest.FromString,
                    response_serializer=search__pb2.SearchResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=search__pb2.EmbedRequest.FromString,
                    response_serializer=search__pb2.EmbedResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=search__pb2.HealthRequest.FromString,
                    response_serializer=search__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'slashus.search.v1.VectorSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('slashus.search.v1.VectorSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorSearch:
    """Vector search, owned by embedding-service.

    embedding-service owns Qdrant, the BGE-M3 model, and the sparse vocab.
    Nothing else touches them. Before this, agentic-service loaded its own copy
    of BGE-M3 (~2.2 GB) and read the same vocab file from a second mount — two
    models on an 8 GB VM, and a vocab that silently went stale in the reader
    whenever ingest appended to it.

    Regenerate stubs after editing:
    python -m grpc_tools.protoc -I shared/proto \
    --python_out=<svc> --grpc_python_out=<svc> shared/proto/search.proto

    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slashus.search.v1.VectorSearch/Search',
            search__pb2.SearchRequest.SerializeToString,
            search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slashus.search.v1.VectorSearch/Embed',
            search__pb2.EmbedRequest.SerializeToString,
            search__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/slashus.search.v1.VectorSearch/Health',
            search__pb2.HealthRequest.SerializeToString,
            search__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
