name: Mirror SLASHUS Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  mirror:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Push frontend to mirror repo
        run: |
          git config --global user.name "Naviya-C-github-action"
          git config --global user.email "naviyac491@gmail.com"

          git clone https://x-access-token:${{ secrets.SLASHUS_PAT_SECRET }}@github.com/Naviya-C/slashus-frontend.git mirror

          rsync -av --delete --exclude='.git/' frontend/ mirror/

          cd mirror
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Mirror frontend from monorepo"
          git push origin main